[program:mycomputer-default]
command=php /var/www/html/artisan queue:work redis --queue=default --sleep=3 --tries=3 --timeout=300
directory=/var/www/html
autostart=true
autorestart=true
stopwaitsecs=3600
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-default.log

[program:mycomputer-emails]
command=php /var/www/html/artisan queue:work redis --queue=emails --sleep=3 --tries=3 --timeout=180
directory=/var/www/html
autostart=true
autorestart=true
stopwaitsecs=3600
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-emails.log

[program:mycomputer-loyalty]
command=php /var/www/html/artisan queue:work redis --queue=loyalty --sleep=3 --tries=3 --timeout=180
directory=/var/www/html
autostart=true
autorestart=true
stopwaitsecs=3600
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-loyalty.log

[program:mycomputer-imports]
command=php /var/www/html/artisan queue:work redis --queue=imports --sleep=3 --tries=3 --timeout=1200
directory=/var/www/html
autostart=true
autorestart=true
stopwaitsecs=3600
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-imports.log

[program:mycomputer-exports]
command=php /var/www/html/artisan queue:work redis --queue=exports --sleep=3 --tries=3 --timeout=900
directory=/var/www/html
autostart=true
autorestart=true
stopwaitsecs=3600
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-exports.log

[program:mycomputer-sync]
command=php /var/www/html/artisan queue:work redis --queue=sync --sleep=3 --tries=5 --timeout=300
directory=/var/www/html
autostart=true
autorestart=true
stopwaitsecs=3600
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-sync.log

[program:mycomputer-analytics]
command=php /var/www/html/artisan queue:work redis --queue=analytics --sleep=3 --tries=5 --timeout=180
directory=/var/www/html
autostart=true
autorestart=true
stopwaitsecs=3600
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-analytics.log
